openapi: 3.1.1

info: 
  title: API first
  version: 1.0.0
  description: API first
servers: 
  - url: https://localhost:3000
paths: 
  /hello:
    get: 
      summary: Holi, mundillo ;) 
      responses: 
        '200':
          description: A successful response
          content: 
            application/json: 
              schema: 
                $ref: '#/components/schemas/HelloResponse'
components: 
  schemas: 
    HelloResponse: 
      type: string