openapi: 3.1.1

info: 
  title: API first
  version: 1.0.0
  description: API first
servers: 
  - url: http://localhost:3000
components: 
  schemas: 
    Home: 
      type: object
    HelloResponse: 
      type: object
paths: 
  /:
    get: 
      summary: Raiz del proyecto
      responses: 
        '200': 
          description: Una respuesta exitosa
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/Home'
  /hello:
    get: 
      summary: Holi, mundillo ;) 
      responses: 
        '200':
          description: A successful response
          content: 
            application/json: 
              schema: 
                $ref: '#/components/schemas/HelloResponse'
  /users: 
    post: 
      summary: Aquí posteamos los usuarios
      requestBody: 
        required: true
        content: 
          application/json:
            schema: 
              type: object
              required: 
              - name
              - age
              - email
              properties: 
                name: 
                  type: string
                  minLength: 2
                age: 
                  type: integer
                  minimum: 18
                email: 
                  type: string
                  format: email
      responses: 
        '201':
          description: Usuario creado
          content:
            application/json: 
              schema: 
                type: object
                properties:
                  id: 
                    type: string
                  name: 
                    type: string
                  age: 
                    type: integer
                  email: 
                    type: string